### PR TITLE
🐛 fix auth issue with invalid accesstoken

### LINKED ISSUE #727: Koa Session Cookie Blocking Reinstallation
## Overview

When using @shopify/koa-shopify-auth to handle auth for my Shopify App, I was unable to reinstall the app, after uninstalling it, without first clearing the browser cache. After some troubleshooting, it seems that that the browser will pass the expired koa session cookies with the reinstallation attempt, which results in a failed redirect.

I'm wondering if anybody else has run into this issue.

### PR DESCRIPTION
**Pull request by katiedavis**
## Description

Fixes #727 

## Type of change
In the koa-shopify-auth package, users were having issues reinstalling their apps via the partner dashboard. This PR adds a call to the admin API (I tried to find the 'cheapest' call) to check the validity of the access token. This solve the issue of users not being able to reinstall the app on their stores. 

I'm looking for feedback on this. If anyone knows a better way of checking if an access token is valid please let me know! 

- [x] koa-shopify-auth Patch: Bug/ Documentation fix (non-breaking change which fixes an issue or adds documentation)

## Checklist

- [x] I have added a changelog entry, prefixed by the type of change noted above
- [x] I have prefixed my pull request title with the corresponding emoji from [this guide](https://gitmoji.carloscuesta.me/)

### CODE REVIEW

File: packages/koa-shopify-auth/src/verify-request/verify-request.ts [hunk 1]
```diff
@@ -23,6 +22,20 @@ export default function verifyRequest({
 
     if (session && session.accessToken) {
       ctx.cookies.set(TOP_LEVEL_OAUTH_COOKIE_NAME);
+      // we need to check if the accessToken is valid.
+      const response = await fetch(`https://${shop}/admin/metafields.json`, {
```
Comment (TheMallen) [inline packages/koa-shopify-auth/src/verify-request/verify-request.ts]: nit: we have constants for these things in  `@shopify/network` under

eg.
```ts
import {Method, Header} from '@shopify/network';
```

```ts
method: Method.Post
headers: {
  [Header.ContentType]: 'application/json',
 ```

File: packages/koa-shopify-auth/src/verify-request/verify-request.ts [hunk 2]
```diff
@@ -23,6 +22,20 @@ export default function verifyRequest({
...
+        method: 'POST',
+        headers: {
+          'Content-Type': 'application/json',
+          'X-Shopify-Access-Token': session.accessToken,
+        },
+      });
+
+      if (response.status === 401) {
+        ctx.redirect(`${authRoute}?shop=${shop}`);
```
Comment (tylerball) [inline packages/koa-shopify-auth/src/verify-request/verify-request.ts]: let's make this redirect string a shared const

File: packages/koa-shopify-auth/src/verify-request/verify-request.ts [hunk 3]
```diff
@@ -23,6 +22,20 @@ export default function verifyRequest({
 
     if (session && session.accessToken) {
       ctx.cookies.set(TOP_LEVEL_OAUTH_COOKIE_NAME);
+      // we need to check if the accessToken is valid.
```
Comment (TheMallen) [inline packages/koa-shopify-auth/src/verify-request/verify-request.ts]: I'd prefer if this comment was a tiny bit more detailed as to why we have to do it

File: packages/koa-shopify-auth/src/verify-request/verify-request.ts [hunk 4]
```diff
@@ -23,6 +22,20 @@ export default function verifyRequest({
...
+      const response = await fetch(`https://${shop}/admin/metafields.json`, {
+        method: 'POST',
+        headers: {
+          'Content-Type': 'application/json',
+          'X-Shopify-Access-Token': session.accessToken,
+        },
+      });
+
+      if (response.status === 401) {
```
Comment (TheMallen) [inline packages/koa-shopify-auth/src/verify-request/verify-request.ts]: can use `Status.Unauthorized` here when we bring in the `Status` enum
